name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@main
        with:
          github_user_name: Abhilash-0322
          outputs: dist/github-snake.svg
      - name: Upload Snake
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-snake.svg
